-- V1_0_0__primary_tables.sql 
-- Creates the main tables for the database 

-- ROLLBACK: DROP TABLE IF EXISTS name;
CREATE TABLE IF NOT EXISTS user (
	id INT PRIMARY KEY AUTO_INCREMENT,
	first_name VARCHAR(128) NOT NULL,
	last_name VARCHAR(128) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	phone VARCHAR(32) UNIQUE,
	password VARCHAR(255) NOT NULL,
	date_creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS payment (
	id INT PRIMARY KEY AUTO_INCREMENT,
	date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_mode (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS payment_status (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS invoice (
	id INT PRIMARY KEY AUTO_INCREMENT,
	date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	total DECIMAL(12, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS invoice_status (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS invoice_line (
	id INT PRIMARY KEY AUTO_INCREMENT,
	unit_price DECIMAL(10, 2) NOT NULL,
	quantity INT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS product (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL,
	description VARCHAR(255),
	price DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS supplier (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL,
	email VARCHAR(255),
	phone VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS product_category (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS stock (
	id INT PRIMARY KEY AUTO_INCREMENT,
	quantity_available INT NOT NULL DEFAULT 0,
	quantity_reserved INT NOT NULL DEFAULT 0,
	reorder_threshold INT NOT NULL DEFAULT 0,
	last_update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS menu (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL,
	description VARCHAR(255),
	price_rate DECIMAL(6, 4) NOT NULL DEFAULT 1.0000
);