<?php
return [
    'GET' => [
        '/'                             => ['HomeController', 'home'],
        '/sign-in'                      => ['AuthController', 'viewSignIn'],
        '/sign-up'                      => ['AuthController', 'viewSignUp'],
        '/sign-out'                     => ['AuthController', 'signOut'],
        '/account'                      => ['AuthController', 'viewAccount'],
        '/account-data'                 => ['AuthController', 'getAccountData'],
        '/products'                     => ['ProductController', 'viewProducts'],
        '/product'                      => ['ProductController', 'viewSingleProduct'],
        '/admin-data'                   => ['AdminController', 'getAdminAccess'],
        '/admin'                        => ['AdminController', 'viewAdmin'],
        '/admin/accounts'               => ['AdminController', 'viewAccounts'],
        '/admin/accounts/edit/:id'      => ['AdminController', 'viewEditAccount'],
        '/admin/products'               => ['AdminController', 'viewProducts'],
        '/admin/products/create'        => ['AdminController', 'viewCreateProduct'],
        '/admin/products/edit/:id'      => ['AdminController', 'viewEditProduct'],
        '/admin/suppliers'              => ['AdminController', 'viewSuppliers'],
        '/admin/suppliers/create'       => ['AdminController', 'viewCreateSupplier'],
        '/admin/suppliers/edit/:id'     => ['AdminController', 'viewEditSupplier'],
        '/admin/invoices'               => ['AdminController', 'viewInvoices'],
        '/admin/invoices/details/:id'   => ['AdminController', 'viewInvoiceDetails'],
        '/admin/categories'             => ['AdminController', 'viewCategories'],
    ],
    'POST' => [
        '/sign-in'                      => ['AuthController', 'signIn'],
        '/sign-up'                      => ['AuthController', 'signUp'],
        '/update-account'               => ['AuthController', 'updateAccount'],
        '/admin/accounts/update'        => ['AdminController', 'updateAccountAdmin'],
        '/admin/accounts/delete/:id'    => ['AdminController', 'deleteAccount'],
        '/admin/products/create'        => ['AdminController', 'createProduct'],
        '/admin/products/update'        => ['AdminController', 'updateProduct'],
        '/admin/products/delete/:id'    => ['AdminController', 'deleteProduct'],
        '/admin/suppliers/create'       => ['AdminController', 'createSupplier'],
        '/admin/suppliers/update'       => ['AdminController', 'updateSupplier'],
        '/admin/suppliers/delete/:id'   => ['AdminController', 'deleteSupplier'],
        '/admin/invoices/update-status' => ['AdminController', 'updateInvoiceStatus'],
        '/admin/categories/create'      => ['AdminController', 'createCategory'],
        '/admin/categories/update'      => ['AdminController', 'updateCategory'],
        '/admin/categories/delete/:id'  => ['AdminController', 'deleteCategory'],
    ],
];
